# Generated by Django 3.2.8 on 2021-10-14 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20211013_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usersLiked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
