# Generated by Django 3.2.8 on 2021-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_user_follows',
            field=models.BooleanField(default=False),
        ),
    ]
